unit Unit1;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Forms, Controls, Graphics, Dialogs, StdCtrls;

type
  TWordCard = record
    English: string;
    Japanese: string;
  end;

  TForm1 = class(TForm)
    LabelCard: TLabel;
    ButtonFlip: TButton;
    ButtonNext: TButton;
    procedure FormCreate(Sender: TObject);
    procedure ButtonFlipClick(Sender: TObject);
    procedure ButtonNextClick(Sender: TObject);
    procedure LabelCardClick(Sender: TObject);
  private
    Words: array[0..349] of TWordCard;
    CurrentIndex: Integer;
    CardFlipped: Boolean;
    procedure InitializeWords;
    procedure ShowCard;
    procedure FlipCard;
  public

  end;

var
  Form1: TForm1;

implementation

{$R *.lfm}

procedure TForm1.InitializeWords;
begin
  // 英語で最もよく使われる350単語
  Words[0].English := 'the'; Words[0].Japanese := 'その、あの';
  Words[1].English := 'be'; Words[1].Japanese := 'である、いる';
  Words[2].English := 'to'; Words[2].Japanese := '～へ、～に';
  Words[3].English := 'of'; Words[3].Japanese := '～の';
  Words[4].English := 'and'; Words[4].Japanese := 'そして、～と';
  Words[5].English := 'a'; Words[5].Japanese := '1つの、1人の';
  Words[6].English := 'in'; Words[6].Japanese := '～の中に、～で';
  Words[7].English := 'that'; Words[7].Japanese := 'あれ、その';
  Words[8].English := 'have'; Words[8].Japanese := '持つ、ある';
  Words[9].English := 'I'; Words[9].Japanese := '私は';
  Words[10].English := 'it'; Words[10].Japanese := 'それは';
  Words[11].English := 'for'; Words[11].Japanese := '～のために、～の間';
  Words[12].English := 'not'; Words[12].Japanese := '～ではない';
  Words[13].English := 'on'; Words[13].Japanese := '～の上に、～について';
  Words[14].English := 'with'; Words[14].Japanese := '～と一緒に、～で';
  Words[15].English := 'he'; Words[15].Japanese := '彼は';
  Words[16].English := 'as'; Words[16].Japanese := '～として、～のように';
  Words[17].English := 'you'; Words[17].Japanese := 'あなたは、あなたたちは';
  Words[18].English := 'do'; Words[18].Japanese := 'する、行う';
  Words[19].English := 'at'; Words[19].Japanese := '～に、～で';
  Words[20].English := 'this'; Words[20].Japanese := 'これ、この';
  Words[21].English := 'but'; Words[21].Japanese := 'しかし、でも';
  Words[22].English := 'his'; Words[22].Japanese := '彼の';
  Words[23].English := 'from'; Words[23].Japanese := '～から、～より';
  Words[24].English := 'they'; Words[24].Japanese := '彼らは';
  Words[25].English := 'we'; Words[25].Japanese := '私たちは';
  Words[26].English := 'say'; Words[26].Japanese := '言う';
  Words[27].English := 'her'; Words[27].Japanese := '彼女の、彼女を';
  Words[28].English := 'she'; Words[28].Japanese := '彼女は';
  Words[29].English := 'or'; Words[29].Japanese := 'または、あるいは';
  Words[30].English := 'an'; Words[30].Japanese := '1つの、1人の';
  Words[31].English := 'will'; Words[31].Japanese := '～するだろう、意志';
  Words[32].English := 'my'; Words[32].Japanese := '私の';
  Words[33].English := 'one'; Words[33].Japanese := '1つ、1人';
  Words[34].English := 'all'; Words[34].Japanese := 'すべての、全部';
  Words[35].English := 'would'; Words[35].Japanese := '～だろう、～するつもり';
  Words[36].English := 'there'; Words[36].Japanese := 'そこに、あそこに';
  Words[37].English := 'their'; Words[37].Japanese := '彼らの';
  Words[38].English := 'what'; Words[38].Japanese := '何、どんな';
  Words[39].English := 'so'; Words[39].Japanese := 'そう、だから';
  Words[40].English := 'up'; Words[40].Japanese := '上に、上がって';
  Words[41].English := 'out'; Words[41].Japanese := '外に、出て';
  Words[42].English := 'if'; Words[42].Japanese := 'もし～なら';
  Words[43].English := 'about'; Words[43].Japanese := '～について、約';
  Words[44].English := 'who'; Words[44].Japanese := '誰が、誰を';
  Words[45].English := 'get'; Words[45].Japanese := '得る、手に入れる';
  Words[46].English := 'which'; Words[46].Japanese := 'どちら、どれ';
  Words[47].English := 'go'; Words[47].Japanese := '行く';
  Words[48].English := 'me'; Words[48].Japanese := '私を、私に';
  Words[49].English := 'when'; Words[49].Japanese := 'いつ、～のとき';
  Words[50].English := 'make'; Words[50].Japanese := '作る、～させる';
  Words[51].English := 'can'; Words[51].Japanese := '～できる、可能';
  Words[52].English := 'like'; Words[52].Japanese := '好き、～のような';
  Words[53].English := 'time'; Words[53].Japanese := '時間、回';
  Words[54].English := 'no'; Words[54].Japanese := 'いいえ、ない';
  Words[55].English := 'just'; Words[55].Japanese := 'ちょうど、ただ';
  Words[56].English := 'him'; Words[56].Japanese := '彼を、彼に';
  Words[57].English := 'know'; Words[57].Japanese := '知っている';
  Words[58].English := 'take'; Words[58].Japanese := '取る、連れて行く';
  Words[59].English := 'people'; Words[59].Japanese := '人々、人';
  Words[60].English := 'into'; Words[60].Japanese := '～の中へ';
  Words[61].English := 'year'; Words[61].Japanese := '年';
  Words[62].English := 'your'; Words[62].Japanese := 'あなたの';
  Words[63].English := 'good'; Words[63].Japanese := '良い、いい';
  Words[64].English := 'some'; Words[64].Japanese := 'いくつかの、いくらか';
  Words[65].English := 'could'; Words[65].Japanese := '～できた、～かもしれない';
  Words[66].English := 'them'; Words[66].Japanese := '彼らを、彼らに';
  Words[67].English := 'see'; Words[67].Japanese := '見る';
  Words[68].English := 'other'; Words[68].Japanese := '他の、別の';
  Words[69].English := 'than'; Words[69].Japanese := '～より、～よりも';
  Words[70].English := 'then'; Words[70].Japanese := 'それから、そのとき';
  Words[71].English := 'now'; Words[71].Japanese := '今、現在';
  Words[72].English := 'look'; Words[72].Japanese := '見る、見える';
  Words[73].English := 'only'; Words[73].Japanese := 'だけ、唯一の';
  Words[74].English := 'come'; Words[74].Japanese := '来る';
  Words[75].English := 'its'; Words[75].Japanese := 'それの';
  Words[76].English := 'over'; Words[76].Japanese := '～の上に、終わって';
  Words[77].English := 'think'; Words[77].Japanese := '考える、思う';
  Words[78].English := 'also'; Words[78].Japanese := 'また、～も';
  Words[79].English := 'back'; Words[79].Japanese := '後ろに、戻って';
  Words[80].English := 'after'; Words[80].Japanese := '～の後で';
  Words[81].English := 'use'; Words[81].Japanese := '使う、使用する';
  Words[82].English := 'two'; Words[82].Japanese := '2つ、2人';
  Words[83].English := 'how'; Words[83].Japanese := 'どのように、どう';
  Words[84].English := 'our'; Words[84].Japanese := '私たちの';
  Words[85].English := 'work'; Words[85].Japanese := '働く、仕事';
  Words[86].English := 'first'; Words[86].Japanese := '最初の、1番目';
  Words[87].English := 'well'; Words[87].Japanese := 'よく、上手に';
  Words[88].English := 'way'; Words[88].Japanese := '道、方法';
  Words[89].English := 'even'; Words[89].Japanese := '～でさえ、さらに';
  Words[90].English := 'new'; Words[90].Japanese := '新しい';
  Words[91].English := 'want'; Words[91].Japanese := '欲しい、～したい';
  Words[92].English := 'because'; Words[92].Japanese := 'なぜなら、～だから';
  Words[93].English := 'any'; Words[93].Japanese := 'どんな、いくつかの';
  Words[94].English := 'these'; Words[94].Japanese := 'これらは';
  Words[95].English := 'give'; Words[95].Japanese := '与える';
  Words[96].English := 'day'; Words[96].Japanese := '日、1日';
  Words[97].English := 'most'; Words[97].Japanese := '最も、たいてい';
  Words[98].English := 'us'; Words[98].Japanese := '私たちを、私たちに';
  Words[99].English := 'is'; Words[99].Japanese := '～である（be動詞）';
  Words[100].English := 'are'; Words[100].Japanese := '～である（be動詞）';
  Words[101].English := 'was'; Words[101].Japanese := '～であった（be動詞）';
  Words[102].English := 'were'; Words[102].Japanese := '～であった（be動詞）';
  Words[103].English := 'been'; Words[103].Japanese := '～であった（be動詞）';
  Words[104].English := 'being'; Words[104].Japanese := '～であること（be動詞）';
  Words[105].English := 'have'; Words[105].Japanese := '持っている、ある';
  Words[106].English := 'has'; Words[106].Japanese := '持っている、ある';
  Words[107].English := 'had'; Words[107].Japanese := '持っていた、あった';
  Words[108].English := 'having'; Words[108].Japanese := '持っていること';
  Words[109].English := 'do'; Words[109].Japanese := 'する';
  Words[110].English := 'does'; Words[110].Japanese := 'する';
  Words[111].English := 'did'; Words[111].Japanese := 'した';
  Words[112].English := 'done'; Words[112].Japanese := 'した、完了した';
  Words[113].English := 'doing'; Words[113].Japanese := 'していること';
  Words[114].English := 'will'; Words[114].Japanese := '～するだろう';
  Words[115].English := 'would'; Words[115].Japanese := '～するだろう';
  Words[116].English := 'should'; Words[116].Japanese := '～すべき';
  Words[117].English := 'could'; Words[117].Japanese := '～できた';
  Words[118].English := 'may'; Words[118].Japanese := '～かもしれない';
  Words[119].English := 'might'; Words[119].Japanese := '～かもしれない';
  Words[120].English := 'must'; Words[120].Japanese := '～しなければならない';
  Words[121].English := 'shall'; Words[121].Japanese := '～するだろう';
  Words[122].English := 'can'; Words[122].Japanese := '～できる';
  Words[123].English := 'cannot'; Words[123].Japanese := '～できない';
  Words[124].English := 'could'; Words[124].Japanese := '～できた';
  Words[125].English := 'should'; Words[125].Japanese := '～すべき';
  Words[126].English := 'would'; Words[126].Japanese := '～するだろう';
  Words[127].English := 'may'; Words[127].Japanese := '～かもしれない';
  Words[128].English := 'might'; Words[128].Japanese := '～かもしれない';
  Words[129].English := 'must'; Words[129].Japanese := '～しなければならない';
  Words[130].English := 'apple'; Words[130].Japanese := 'りんご';
  Words[131].English := 'book'; Words[131].Japanese := '本';
  Words[132].English := 'car'; Words[132].Japanese := '車';
  Words[133].English := 'dog'; Words[133].Japanese := '犬';
  Words[134].English := 'eye'; Words[134].Japanese := '目';
  Words[135].English := 'face'; Words[135].Japanese := '顔';
  Words[136].English := 'girl'; Words[136].Japanese := '女の子';
  Words[137].English := 'hand'; Words[137].Japanese := '手';
  Words[138].English := 'home'; Words[138].Japanese := '家';
  Words[139].English := 'house'; Words[139].Japanese := '家';
  Words[140].English := 'life'; Words[140].Japanese := '人生、命';
  Words[141].English := 'man'; Words[141].Japanese := '男、男性';
  Words[142].English := 'name'; Words[142].Japanese := '名前';
  Words[143].English := 'night'; Words[143].Japanese := '夜';
  Words[144].English := 'part'; Words[144].Japanese := '部分';
  Words[145].English := 'place'; Words[145].Japanese := '場所';
  Words[146].English := 'room'; Words[146].Japanese := '部屋';
  Words[147].English := 'school'; Words[147].Japanese := '学校';
  Words[148].English := 'side'; Words[148].Japanese := '側、辺';
  Words[149].English := 'thing'; Words[149].Japanese := '物、こと';
  Words[150].English := 'water'; Words[150].Japanese := '水';
  Words[151].English := 'world'; Words[151].Japanese := '世界';
  Words[152].English := 'way'; Words[152].Japanese := '道、方法';
  Words[153].English := 'week'; Words[153].Japanese := '週';
  Words[154].English := 'word'; Words[154].Japanese := '言葉';
  Words[155].English := 'world'; Words[155].Japanese := '世界';
  Words[156].English := 'year'; Words[156].Japanese := '年';
  Words[157].English := 'big'; Words[157].Japanese := '大きい';
  Words[158].English := 'black'; Words[158].Japanese := '黒い';
  Words[159].English := 'blue'; Words[159].Japanese := '青い';
  Words[160].English := 'brown'; Words[160].Japanese := '茶色の';
  Words[161].English := 'cold'; Words[161].Japanese := '寒い、冷たい';
  Words[162].English := 'different'; Words[162].Japanese := '違う、異なる';
  Words[163].English := 'early'; Words[163].Japanese := '早い';
  Words[164].English := 'easy'; Words[164].Japanese := '簡単な';
  Words[165].English := 'free'; Words[165].Japanese := '自由な、無料の';
  Words[166].English := 'full'; Words[166].Japanese := '満杯の、いっぱいの';
  Words[167].English := 'great'; Words[167].Japanese := '素晴らしい、大きい';
  Words[168].English := 'green'; Words[168].Japanese := '緑の';
  Words[169].English := 'hard'; Words[169].Japanese := '硬い、難しい';
  Words[170].English := 'high'; Words[170].Japanese := '高い';
  Words[171].English := 'hot'; Words[171].Japanese := '熱い、暑い';
  Words[172].English := 'important'; Words[172].Japanese := '重要な';
  Words[173].English := 'large'; Words[173].Japanese := '大きい';
  Words[174].English := 'late'; Words[174].Japanese := '遅い、遅れた';
  Words[175].English := 'left'; Words[175].Japanese := '左の';
  Words[176].English := 'little'; Words[176].Japanese := '小さい、少し';
  Words[177].English := 'long'; Words[177].Japanese := '長い';
  Words[178].English := 'low'; Words[178].Japanese := '低い';
  Words[179].English := 'new'; Words[179].Japanese := '新しい';
  Words[180].English := 'next'; Words[180].Japanese := '次の';
  Words[181].English := 'old'; Words[181].Japanese := '古い、年を取った';
  Words[182].English := 'open'; Words[182].Japanese := '開いている';
  Words[183].English := 'own'; Words[183].Japanese := '自分の';
  Words[184].English := 'public'; Words[184].Japanese := '公共の、公開の';
  Words[185].English := 'red'; Words[185].Japanese := '赤い';
  Words[186].English := 'right'; Words[186].Japanese := '右の、正しい';
  Words[187].English := 'small'; Words[187].Japanese := '小さい';
  Words[188].English := 'sure'; Words[188].Japanese := '確かな、確信して';
  Words[189].English := 'white'; Words[189].Japanese := '白い';
  Words[190].English := 'young'; Words[190].Japanese := '若い';
  Words[191].English := 'ask'; Words[191].Japanese := '尋ねる、頼む';
  Words[192].English := 'become'; Words[192].Japanese := '～になる';
  Words[193].English := 'begin'; Words[193].Japanese := '始める';
  Words[194].English := 'call'; Words[194].Japanese := '呼ぶ、電話する';
  Words[195].English := 'change'; Words[195].Japanese := '変える、変化する';
  Words[196].English := 'come'; Words[196].Japanese := '来る';
  Words[197].English := 'feel'; Words[197].Japanese := '感じる';
  Words[198].English := 'find'; Words[198].Japanese := '見つける';
  Words[199].English := 'get'; Words[199].Japanese := '得る、手に入れる';
  Words[200].English := 'give'; Words[200].Japanese := '与える';
  Words[201].English := 'go'; Words[201].Japanese := '行く';
  Words[202].English := 'help'; Words[202].Japanese := '助ける、手伝う';
  Words[203].English := 'keep'; Words[203].Japanese := '保つ、続ける';
  Words[204].English := 'know'; Words[204].Japanese := '知っている';
  Words[205].English := 'leave'; Words[205].Japanese := '去る、残す';
  Words[206].English := 'let'; Words[206].Japanese := '～させる、許す';
  Words[207].English := 'live'; Words[207].Japanese := '生きる、住む';
  Words[208].English := 'look'; Words[208].Japanese := '見る';
  Words[209].English := 'make'; Words[209].Japanese := '作る、～させる';
  Words[210].English := 'move'; Words[210].Japanese := '動く、引っ越す';
  Words[211].English := 'need'; Words[211].Japanese := '必要とする';
  Words[212].English := 'play'; Words[212].Japanese := '遊ぶ、演奏する';
  Words[213].English := 'put'; Words[213].Japanese := '置く';
  Words[214].English := 'run'; Words[214].Japanese := '走る';
  Words[215].English := 'say'; Words[215].Japanese := '言う';
  Words[216].English := 'see'; Words[216].Japanese := '見る';
  Words[217].English := 'seem'; Words[217].Japanese := '～のように見える';
  Words[218].English := 'show'; Words[218].Japanese := '見せる、示す';
  Words[219].English := 'start'; Words[219].Japanese := '始める';
  Words[220].English := 'take'; Words[220].Japanese := '取る、連れて行く';
  Words[221].English := 'tell'; Words[221].Japanese := '話す、伝える';
  Words[222].English := 'think'; Words[222].Japanese := '考える、思う';
  Words[223].English := 'try'; Words[223].Japanese := '試す、努力する';
  Words[224].English := 'turn'; Words[224].Japanese := '回る、変わる';
  Words[225].English := 'use'; Words[225].Japanese := '使う';
  Words[226].English := 'walk'; Words[226].Japanese := '歩く';
  Words[227].English := 'want'; Words[227].Japanese := '欲しい、～したい';
  Words[228].English := 'work'; Words[228].Japanese := '働く';
  Words[229].English := 'write'; Words[229].Japanese := '書く';
  Words[230].English := 'again'; Words[230].Japanese := 'また、再び';
  Words[231].English := 'always'; Words[231].Japanese := 'いつも、常に';
  Words[232].English := 'away'; Words[232].Japanese := '離れて、不在で';
  Words[233].English := 'back'; Words[233].Japanese := '後ろに、戻って';
  Words[234].English := 'down'; Words[234].Japanese := '下に、下がって';
  Words[235].English := 'early'; Words[235].Japanese := '早く';
  Words[236].English := 'far'; Words[236].Japanese := '遠くに';
  Words[237].English := 'fast'; Words[237].Japanese := '速く';
  Words[238].English := 'here'; Words[238].Japanese := 'ここに';
  Words[239].English := 'how'; Words[239].Japanese := 'どのように';
  Words[240].English := 'long'; Words[240].Japanese := '長く、どのくらい';
  Words[241].English := 'more'; Words[241].Japanese := 'もっと、さらに';
  Words[242].English := 'most'; Words[242].Japanese := '最も、たいてい';
  Words[243].English := 'much'; Words[243].Japanese := 'たくさん、非常に';
  Words[244].English := 'never'; Words[244].Japanese := '決して～ない';
  Words[245].English := 'now'; Words[245].Japanese := '今、現在';
  Words[246].English := 'often'; Words[246].Japanese := 'しばしば、よく';
  Words[247].English := 'once'; Words[247].Japanese := '一度、かつて';
  Words[248].English := 'quickly'; Words[248].Japanese := '速く、すぐに';
  Words[249].English := 'quite'; Words[249].Japanese := 'かなり、完全に';
  Words[250].English := 'really'; Words[250].Japanese := '本当に、実際に';
  Words[251].English := 'slowly'; Words[251].Japanese := 'ゆっくりと';
  Words[252].English := 'so'; Words[252].Japanese := 'そう、だから';
  Words[253].English := 'sometimes'; Words[253].Japanese := '時々';
  Words[254].English := 'still'; Words[254].Japanese := 'まだ、依然として';
  Words[255].English := 'then'; Words[255].Japanese := 'それから、そのとき';
  Words[256].English := 'there'; Words[256].Japanese := 'そこに';
  Words[257].English := 'today'; Words[257].Japanese := '今日';
  Words[258].English := 'together'; Words[258].Japanese := '一緒に';
  Words[259].English := 'too'; Words[259].Japanese := '～も、あまりに';
  Words[260].English := 'very'; Words[260].Japanese := 'とても、非常に';
  Words[261].English := 'well'; Words[261].Japanese := 'よく、上手に';
  Words[262].English := 'when'; Words[262].Japanese := 'いつ、～のとき';
  Words[263].English := 'where'; Words[263].Japanese := 'どこに、どこで';
  Words[264].English := 'why'; Words[264].Japanese := 'なぜ、どうして';
  Words[265].English := 'yes'; Words[265].Japanese := 'はい、そうです';
  Words[266].English := 'yesterday'; Words[266].Japanese := '昨日';
  Words[267].English := 'yet'; Words[267].Japanese := 'まだ、しかし';
  Words[268].English := 'above'; Words[268].Japanese := '～の上に';
  Words[269].English := 'across'; Words[269].Japanese := '横切って、向こう側に';
  Words[270].English := 'after'; Words[270].Japanese := '～の後で';
  Words[271].English := 'against'; Words[271].Japanese := '～に反対して、～に対して';
  Words[272].English := 'along'; Words[272].Japanese := '～に沿って';
  Words[273].English := 'among'; Words[273].Japanese := '～の間で';
  Words[274].English := 'around'; Words[274].Japanese := '～の周りに、約';
  Words[275].English := 'at'; Words[275].Japanese := '～に、～で';
  Words[276].English := 'before'; Words[276].Japanese := '～の前に';
  Words[277].English := 'behind'; Words[277].Japanese := '～の後ろに';
  Words[278].English := 'below'; Words[278].Japanese := '～の下に';
  Words[279].English := 'beside'; Words[279].Japanese := '～の横に';
  Words[280].English := 'between'; Words[280].Japanese := '～の間で';
  Words[281].English := 'by'; Words[281].Japanese := '～によって、～のそばに';
  Words[282].English := 'during'; Words[282].Japanese := '～の間';
  Words[283].English := 'except'; Words[283].Japanese := '～を除いて';
  Words[284].English := 'for'; Words[284].Japanese := '～のために、～の間';
  Words[285].English := 'from'; Words[285].Japanese := '～から';
  Words[286].English := 'in'; Words[286].Japanese := '～の中に、～で';
  Words[287].English := 'inside'; Words[287].Japanese := '～の中に';
  Words[288].English := 'into'; Words[288].Japanese := '～の中へ';
  Words[289].English := 'near'; Words[289].Japanese := '～の近くに';
  Words[290].English := 'of'; Words[290].Japanese := '～の';
  Words[291].English := 'off'; Words[291].Japanese := '～から離れて';
  Words[292].English := 'on'; Words[292].Japanese := '～の上に、～について';
  Words[293].English := 'onto'; Words[293].Japanese := '～の上へ';
  Words[294].English := 'outside'; Words[294].Japanese := '～の外に';
  Words[295].English := 'over'; Words[295].Japanese := '～の上に、終わって';
  Words[296].English := 'past'; Words[296].Japanese := '～を過ぎて';
  Words[297].English := 'since'; Words[297].Japanese := '～以来';
  Words[298].English := 'through'; Words[298].Japanese := '～を通って';
  Words[299].English := 'throughout'; Words[299].Japanese := '～の間ずっと';
  Words[300].English := 'to'; Words[300].Japanese := '～へ、～に';
  Words[301].English := 'toward'; Words[301].Japanese := '～の方へ';
  Words[302].English := 'under'; Words[302].Japanese := '～の下に';
  Words[303].English := 'until'; Words[303].Japanese := '～まで';
  Words[304].English := 'up'; Words[304].Japanese := '上に、上がって';
  Words[305].English := 'upon'; Words[305].Japanese := '～の上に';
  Words[306].English := 'with'; Words[306].Japanese := '～と一緒に、～で';
  Words[307].English := 'within'; Words[307].Japanese := '～の中に';
  Words[308].English := 'without'; Words[308].Japanese := '～なしで';
  Words[309].English := 'about'; Words[309].Japanese := '～について、約';
  Words[310].English := 'above'; Words[310].Japanese := '～の上に';
  Words[311].English := 'across'; Words[311].Japanese := '横切って';
  Words[312].English := 'after'; Words[312].Japanese := '～の後で';
  Words[313].English := 'again'; Words[313].Japanese := 'また、再び';
  Words[314].English := 'against'; Words[314].Japanese := '～に反対して';
  Words[315].English := 'all'; Words[315].Japanese := 'すべての';
  Words[316].English := 'almost'; Words[316].Japanese := 'ほとんど';
  Words[317].English := 'alone'; Words[317].Japanese := '一人で';
  Words[318].English := 'along'; Words[318].Japanese := '～に沿って';
  Words[319].English := 'already'; Words[319].Japanese := 'すでに';
  Words[320].English := 'also'; Words[320].Japanese := 'また、～も';
  Words[321].English := 'although'; Words[321].Japanese := '～だけれども';
  Words[322].English := 'always'; Words[322].Japanese := 'いつも';
  Words[323].English := 'and'; Words[323].Japanese := 'そして、～と';
  Words[324].English := 'another'; Words[324].Japanese := 'もう一つの';
  Words[325].English := 'any'; Words[325].Japanese := 'どんな、いくつかの';
  Words[326].English := 'anyone'; Words[326].Japanese := '誰でも';
  Words[327].English := 'anything'; Words[327].Japanese := '何でも';
  Words[328].English := 'anywhere'; Words[328].Japanese := 'どこでも';
  Words[329].English := 'appear'; Words[329].Japanese := '現れる、見える';
  Words[330].English := 'around'; Words[330].Japanese := '～の周りに';
  Words[331].English := 'ask'; Words[331].Japanese := '尋ねる';
  Words[332].English := 'away'; Words[332].Japanese := '離れて';
  Words[333].English := 'back'; Words[333].Japanese := '後ろに';
  Words[334].English := 'bad'; Words[334].Japanese := '悪い';
  Words[335].English := 'be'; Words[335].Japanese := 'である、いる';
  Words[336].English := 'beautiful'; Words[336].Japanese := '美しい';
  Words[337].English := 'become'; Words[337].Japanese := '～になる';
  Words[338].English := 'bed'; Words[338].Japanese := 'ベッド';
  Words[339].English := 'been'; Words[339].Japanese := '～であった';
  Words[340].English := 'before'; Words[340].Japanese := '～の前に';
  Words[341].English := 'began'; Words[341].Japanese := '始めた';
  Words[342].English := 'begin'; Words[342].Japanese := '始める';
  Words[343].English := 'behind'; Words[343].Japanese := '～の後ろに';
  Words[344].English := 'being'; Words[344].Japanese := '～であること';
  Words[345].English := 'believe'; Words[345].Japanese := '信じる';
  Words[346].English := 'below'; Words[346].Japanese := '～の下に';
  Words[347].English := 'beside'; Words[347].Japanese := '～の横に';
  Words[348].English := 'best'; Words[348].Japanese := '最高の、最善の';
  Words[349].English := 'better'; Words[349].Japanese := 'より良い';
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  InitializeWords;
  CurrentIndex := 0;
  CardFlipped := False;
  ShowCard;
end;

procedure TForm1.ShowCard;
begin
  if CardFlipped then
    LabelCard.Caption := Words[CurrentIndex].Japanese
  else
    LabelCard.Caption := Words[CurrentIndex].English;
end;

procedure TForm1.FlipCard;
begin
  CardFlipped := not CardFlipped;
  ShowCard;
end;

procedure TForm1.ButtonFlipClick(Sender: TObject);
begin
  FlipCard;
end;

procedure TForm1.ButtonNextClick(Sender: TObject);
begin
  CardFlipped := False;
  CurrentIndex := (CurrentIndex + 1) mod 350;
  ShowCard;
end;

procedure TForm1.LabelCardClick(Sender: TObject);
begin
  FlipCard;
end;

end.

